name: Deploy Dataflow Streaming Pipeline (Classic Template)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write GCP credentials file
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > ${{ github.workspace }}/gcloud-key.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcloud-key.json
          gcloud config set project airy-actor-457907-a8
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud-key.json

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: airy-actor-457907-a8
          install_components: 'beta'

      - name: Build Classic Template (Streaming Pipeline)
        run: |
          python dataflow_pipeline.py \
            --runner=DataflowRunner \
            --project=airy-actor-457907-a8 \
            --region=us-central1 \
            --temp_location=gs://raw-bucket-1/temp \
            --staging_location=gs://raw-bucket-1/staging \
            --template_location=gs://raw-bucket-1/templates/streaming_template

      - name: Launch Streaming Job from Template (Non-Blocking)
        run: |
          gcloud dataflow jobs run "streaming-job-$(date +%s)" \
            --gcs-location=gs://raw-bucket-1/templates/streaming_template \
            --region=us-central1 \
            --async
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud-key.json