name: Deploy Dataproc Job and DAG

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Upload Spark Job to GCS
        run: |
          gsutil cp spark_jobs/main_job.py gs://sample-data-for-pract1/spark_jobs/

      - name: Upload Airflow DAG to Composer
        run: |
          gsutil cp dags/dataproc_job_dag.py gs://us-central1-sanbox-env-e1b4197d-bucket/dags/